### ISSUE TITLE
feat : 문제 풀이 결과 세분화

### ISSUE THREAD

**Issue by rladmstn** [GAMZA-BAT/ALGOHUB-SERVER#29]
## 📌 Issue

기존 문제 풀이 결과를 Correct, Incorrect로만 분류 했었는데, 이제는 "맞았습니다!!", "런타임 에러", "틀렸습니다", "시간 초과" 등 세분화한 결과로 가져오도록 수정하고자 합니다.

## ✅ TODO

- [x] 풀이 필드 수정하기
- [x] 풀이 생성 시 풀이 결과 수정하기
- [x] 풀이 조회 관련 API 풀이 결과 수정하기

**Comment by rladmstn** [comment]
흠 생각해보니 런타임 에러는 IndexError, RecursionError 이렇게 괄호 안에 써주던데 백준 결과 그대로 저장하는게 나을지 아님 딱 런타임 에러라고만 저장할지 고민이다
