### ISSUE TITLE
feat:공지 조회 API 추가 +submission.json 파일 지우겠습니다

### ISSUE THREAD

**Issue by s-hwan** [GAMZA-BAT/ALGOHUB-SERVER#78]
## 📌 Issue
공지 조회 API 추가 하겠습니다.

## ✅ TODO
- [x] 한 개 조회 API 추가
- [x] 테스트 코드 작성
- [x] submission.json 파일 지우기

**Comment by rladmstn** [comment]
이슈 닫아주세요~!

**Comment by s-hwan** [comment]
> 이슈 닫아주세요~!

ㅋㅋㅋㅋ닫자마자 ㅋㅋㅋㅋㅋㅋㅋ닫았습니다!
